name: Global Ag Teck
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48298065713606775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#335ba6'
    - '#5772b3'
    - '#4664ab'
    - '#c4cae5'
  brandStrength: 1
  lightness: 0.35580524941906333
  saturation: 0.3125
  rhythmicContrast: 0.7661727159284055
purpose: []
